export const ADD_NEW_STATION = 'ADD_NEW_STATION';
export const REMOVE_STATION = 'REMOVE_STATION';
export const UPDATE_STATION = 'UPDATE_STATION';
export const SET_CURRENT_EDITABLE_ITEM = 'SET_CURRENT_EDITABLE_ITEM';
export const UPDATE_LINE = 'UPDATE_LINE';
export const UPDATE_TIMETABLE_CELL = 'UPDATE_TIMETABLE_CELL';
export const SET_CURRENT_EDITABLE_ITEM_BY_INDEX = 'SET_CURRENT_EDITABLE_ITEM_BY_INDEX';
